### ISSUE TITLE
Missing Job dependencies examples

### ISSUE THREAD

**Issue by plstonge** [ComputeCanada/docs#1]
Missing Job dependencies examples. How to submit a sequence of jobs.

**Comment by stubbsda** [comment]
I agree that this should be in the Wiki, though I hesitate to suggest adding it to the page
https://docs.computecanada.ca/wiki/Running_jobs
which is already too long in my opinion.

**Comment by stubbsda** [comment]
For this issue, perhaps you would like to write a brief page Pier-Luc on the subject, entitled "Gestion des dépendances entre tâches" for example (or "Managing inter-job dependencies" if you want to use English)?

**Comment by plstonge** [comment]
@stubbsda ,
Should we go bigger and create an "Advanced job submission" page that would include inter-job dependencies, arrays of jobs and heterogeneous jobs?

**Comment by mboisson** [comment]
I think @coulombec had ideas about that

**Comment by stubbsda** [comment]
We could certainly contemplate a page on advanced job submission, given the exceptional length of the existing (beginners) page. We do already have some "advanced" material on pages like this,
https://docs.computecanada.ca/wiki/Job_scheduling_policies
and
https://docs.computecanada.ca/wiki/Using_GPUs_with_Slurm

**Comment by plstonge** [comment]
"Array job" is already in the Running_jobs page. It is also used to resume a previous job (still in Running_jobs).

1. What is the proper name: "job arrays", "array of jobs" or "array job"? "Job-array"?
EDIT: https://slurm.schedmd.com/job_array.html
2. I believe the Advanced page should only have a link to the Job arrays page.

**Comment by stubbsda** [comment]
I usually say "job array" (pl. job arrays) but I don't know as there is any canonical version, though I see that Slurm uses the same terminology as I do.

**Comment by plstonge** [comment]
The new draft is here:

https://docs-dev.computecanada.ca/wiki/Advanced_Job_Submission

**Comment by stubbsda** [comment]
OK - note that people generally write new pages directly on the main Wiki but include the "{{Draft}}" tag for the page until it's deemed to be ready for use without any warnings. Typically when you remove the {{Draft}} tag you also mark the page for translation.

**Comment by plstonge** [comment]
Done:

https://docs.computecanada.ca/wiki/Advanced_Job_Submission

I believe this issue can be closed until there is another issue regarding this page.
