### ISSUE TITLE
Missing documentation : How to configure ssh-agent

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/docs#10]
Good practice would want users to configure SSH agents when they use SSH keys (rather than generating SSH keys pairs on the cluster), but we have no documentation on that. 

It should also cover using ssh-askpass.

**Comment by stubbsda** [comment]
I guess the logical page for this (for Linux and macOS, at least) would be
https://docs.computecanada.ca/wiki/Using_SSH_keys_in_Linux

**Comment by stubbsda** [comment]
Thinking about this a little more, one wrinkle is that these days most people using Linux or macOS will not directly run ssh-agent but instead the operating system usually provides some kind of GUI-based "keychain manager" that unlocks your SSH keypair when you login to the local machine.

**Comment by stubbsda** [comment]
I have added a section on ssh-agent to the page 
https://docs.computecanada.ca/wiki/Using_SSH_keys_in_Linux#Using_ssh-agent
Feel free to edit, correct, enrich etc. as desired before we mark it for translation.

**Comment by stubbsda** [comment]
Added a section on using ssh-agent to the SSH keys in Linux page.
