### ISSUE TITLE
For an OpenACC reference page

### ISSUE THREAD

**Issue by plstonge** [ComputeCanada/docs#11]
`gcc -fopenacc -march=native -O3 pi.c -o pi`
See Bart's comment on Slack:
https://computecanada.slack.com/archives/C0LKGFVK2/p1605894980071300

There is already an OpenACC tutorial on the wiki, but I believe this information should be in a "reference page" instead of a "tutorial page".

**Comment by stubbsda** [comment]
We do have a CUDA page of course,
https://docs.computecanada.ca/wiki/CUDA
but I wonder if we shouldn't have a more general "Accelerators" (?) page that could also include very basic material on OpenACC or perhaps just a (reference-oriented) OpenACC page?

**Comment by plstonge** [comment]
I was mostly thinking about a standalone OpenACC page. CUDA and OpenACC pages could be part of a group of pages.

**Comment by stubbsda** [comment]
Sure, feel free to such a page "OpenACC" that you can mark as Draft and toss in Bart's minimal pi example. Someone like Nikolai can perhaps work on expanding and enriching it in the coming weeks.

**Comment by plstonge** [comment]
Page created here:
https://docs.computecanada.ca/wiki/OpenACC
It can be reviewed.
