### ISSUE TITLE
OpenStack Flavors

### ISSUE THREAD

**Issue by plstonge** [ComputeCanada/docs#12]
We need to put this command somewhere on the wiki: `openstack flavor list --sort-column RAM`

Either:
* https://docs.computecanada.ca/wiki/Cloud (to help choosing a cloud infrastructure)
* https://docs.computecanada.ca/wiki/OpenStack (next to other `openstack` commands)
* https://docs.computecanada.ca/wiki/Virtual_machine_flavors (or in this page)

**Comment by stubbsda** [comment]
I would be inclined to see it put on the OpenStack page Pier-Luc, given that it's an OpenStack command. Could you add it along with some explanatory text concerning its use?

**Comment by plstonge** [comment]
I have just found this:
* https://docs.computecanada.ca/wiki/OpenStack_Command_Line_Clients#flavor_command_group

Therefore, the only useful location for the command would be in Virtual_machine_flavors, in my opinion.

**Comment by plstonge** [comment]
Done here:
* https://docs.computecanada.ca/wiki/Virtual_machine_flavors
