### ISSUE TITLE
Hiding or making the "Modules" pages non-discoverable

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/docs#13]
Currently, the "Modules_avx512" (and other architecture) pages are searchable and findable, which may mean users find those instead of the Available software page. 

Maybe it is possible to make them non-indexable ? Or have them redirect to the Available software page ?

**Comment by mboisson** [comment]
This information is useful : 
https://www.mediawiki.org/wiki/Help:Controlling_search_engine_indexing

**Comment by mboisson** [comment]
I created the template 
https://docs.computecanada.ca/wiki/Template:NOINDEX

In theory, adding `{{NOINDEX}}` to these pages should make them non-indexable.

**Comment by mboisson** [comment]
This should be solved by https://github.com/ComputeCanada/wiki_module_bot/pull/1

**Comment by mboisson** [comment]
@sergueev can you provide an update ?

**Comment by sergueev** [comment]
Added {{NOINDEX}} to the template for those specific pages (Modules_avx512,Modules_avx2, Modules_avx, Modules_sse3). This should make the pages non discoverable. Pushed all the changes to git. Closing the issue.
