### ISSUE TITLE
Lien brisé sur la page « Demander un compte »

### ISSUE THREAD

**Issue by slanthier1** [ComputeCanada/docs#14]
Sur la page :
- intitulée : Demander un compte  
- URL : https://www.computecanada.ca/page-daccueil-du-portail-de-recherche/account-management/demander-un-compte/?lang=fr

Au 3e paragraphe, le lien :
- libellé : FAQ sur le renouvellement de compte

pointe vers une adresse introuvable, soit 
- https://www.computecanada.ca/research-portal/compte-management/compte-renewals/compte-renewals-faq/

La bonne cible semble être plutôt : 
- https://www.computecanada.ca/page-daccueil-du-portail-de-recherche/account-management/renouvellements-de-compte/faq-sur-les-renouvelements-de-comptes/?lang=fr

**Comment by stubbsda** [comment]
En fait ce problème n'a aucun rapport avec le site de documentation,
https://docs.computecanada.ca/
mais plutôt le site https://www.computecanada.ca. En tout cas, la responsable de communications de Calcul Canada a été notifiée du problème et devrait le corriger sous peu.
