### ISSUE TITLE
Remove owncloud from "Regional partners and services"

### ISSUE THREAD

**Issue by cmd-ntrf** [ComputeCanada/docs#15]
The WestGrid service has been replaced by Compute Canada national nextcloud service.

**Comment by stubbsda** [comment]
So should we put a link to the Nextcloud page in the section "Systems and services" after scrubbing the Owncloud link?

**Comment by cmd-ntrf** [comment]
I think so, yes.

**Comment by stubbsda** [comment]
Done.
