### ISSUE TITLE
Closing docs-dev to public reading

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/docs#16]
@sergueev, please provide updates in here.

**Comment by sergueev** [comment]
One solution for closing docs-dev to public is by setting $wgGroupPermissions['*']['read'] = false in the LocalSettings.php.  It's currently unset as I am experimenting with the modules script and the MW API does not allow transactions if MW is closed for reading. I will block it again when I am done with my tests.

**Comment by sergueev** [comment]
The docs-dev is closed for public reading by setting the $wgGroupPermissions['*']['read'] = false.
