### ISSUE TITLE
Upgrading MediaWiki to 1.31.12

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/docs#17]
Please provide udpates in here @sergueev

**Comment by sergueev** [comment]
I think the newest 1.31.12 version contains several security fixed as compared to ver 1.31.10 so it makes sense to upgrade.
The Upgrade plan for 1.31.12 has been created. 
https://wiki.computecanada.ca/staff/MediaWiki_Upgrade

The process ticket for the Upgrade has also been created.

What remains is installation&testing this 1.31.12 ver on docs-dev.

**Comment by sergueev** [comment]
The MW upgrade to ver 1.31.12 is complete. The MW is working normally, no issues has been detected or reported.
