### ISSUE TITLE
VNC Viewer for Windows - instructions still not clear enough

### ISSUE THREAD

**Issue by plstonge** [ComputeCanada/docs#19]
The syntax of the installer name is too quickly forgotten once we get on the download page and we look for which package should be downloaded. I also believe RealVNC is easier to use.

**Comment by stubbsda** [comment]
It looks like Doug Roberts is the principal author of the page
https://docs.computecanada.ca/wiki/VNC
assuming this is the one you're talking about. Maybe you could talk with him Pier-Luc about changes to the page and replacing the TigerVNC recommendation by RealVNC?

**Comment by plstonge** [comment]
Yes, OK. My plan was to add bullet-points with RealVNC at first and TigerVNC second.

**Comment by plstonge** [comment]
Doug and I have fixed the Windows section. Doug will have to contact Tyson before deciding if we are going to support RealVNC (which will have to work with Gra-VDI, and all VNC servers). To be continued...

**Comment by stubbsda** [comment]
Any progress on this issue, Pier-Luc?

**Comment by plstonge** [comment]
No. We should probably assign this issue to Doug and/or Tyson.

**Comment by plstonge** [comment]
The main problem about instructions for Windows users is fixed. For that reason alone, we may close this issue.

About getting documentation for RealVNC, this would be a good to have, but not critical.

**Comment by stubbsda** [comment]
OK, I will close this issue and you can open a new one if you want about RealVNC.
