### ISSUE TITLE
How to fix GID and SGID recursively

### ISSUE THREAD

**Issue by plstonge** [ComputeCanada/docs#2]
In the Sharing data page, we need a simple procedure to fix common permission issues in project space folders, something like:

```
chgrp -R group_name folder_name
find folder_name -type d -exec chmod g+s {} \;
```

I am just not sure in which section this should be. Maybe in the FAQ?

**Comment by stubbsda** [comment]
I would say add it to the page
https://docs.computecanada.ca/wiki/Project_layout

**Comment by mboisson** [comment]
Already here https://docs.computecanada.ca/wiki/Frequently_Asked_Questions#How_to_fix_the_problem

**Comment by stubbsda** [comment]
I'm going to suppose that we can close this issue, Pier-Luc, unless you have any objections?

**Comment by plstonge** [comment]
I was about to check this today.

**Comment by plstonge** [comment]
OK. The main root cause of this issues is how we find the information. "SGID" was only found on "Sharing data" pages. I have edited the FAQ page in order to include that keyword.
