### ISSUE TITLE
Fix Available Python Wheels page

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/docs#23]
- [x] Re-Condense the python package instead of having one result per line. (`--condense` argument)
- [x] Ensure to show all software stack results and not just 2020 ones. Use `PIP_CONFIG_FILE=""`
- [x] Add to the [github repo ](https://github.com/ComputeCanada/wiki_module_bot)the script file used to generate the page.

**Comment by mboisson** [comment]
The script should be added to this repository: https://github.com/ComputeCanada/wiki_module_bot

**Comment by sergueev** [comment]
Ok, will add the wheels updating script to the same repo (instead of having  separate  repos for modules and wheels) very shortly.

**Comment by sergueev** [comment]
Added script for updating wheels  upload_wheel-to-wikiAPI.sh
to [https://github.com/ComputeCanada/wiki_module_bot](https://github.com/ComputeCanada/wiki_module_bot)

**Comment by ccoulombe** [comment]
@sergueev 

The command is missing :
- the `--condense` option to group software together. As it exists in the commented command on the previous line.

https://github.com/ComputeCanada/wiki_module_bot/blob/b4e83ef9e70243642e1530a1c3fb146c17ba5118/upload_wheel-to-wikiAPI.sh#L60

The command should then be :
```
PIP_CONFIG_FILE="" /cvmfs/soft.computecanada.ca/custom/python/envs/avail_wheels/bin/python3 /cvmfs/soft.computecanada.ca/custom/python/envs/avail_wheels/avail_wheels.py --all-versions --all-arch --python "$VERSION" --mediawiki --column name version --condense > "$WIKITXTFILE.new"
```

**Comment by sergueev** [comment]
Ok, thanks , I will correct it

**Comment by ccoulombe** [comment]
Fixed by https://github.com/ComputeCanada/wiki_module_bot/commit/c306d5df9fde0e2c27a56da9fa3cb8565ad1398c
