### ISSUE TITLE
Upgrading MediaWiki to 1.35.x

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/docs#24]

**Comment by sergueev** [comment]
There was another subversion release - 1.35.3 since we started thinking about upgrading to 1.35. I installed it on docs-dev. Seems to be working just fine. In fact, Lingo extension is not causing problems anymore as it's used in 1.35.2. I think it's safe to schedule an upgrade on production site.

**Comment by mboisson** [comment]
Internal ticket with CAB information: https://support.computecanada.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=133807#565217

**Comment by sergueev** [comment]
The Mediawiki has been upgraded to ver 1.35.3 on docs. The Lingo extension does work. However, the apache ssl_error_log shows lots of warning about undefined indexes and variables  ... The question is how crucial those warnings are and how they may affect the functionality of this extension.

**Comment by mboisson** [comment]
Closing
