### ISSUE TITLE
Using the Compute Canada Single Sign On for MediaWiki

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/docs#25]
We should aim to use the Compute Canada IdP rather than direct LDAP authentication. This will ultimately allow our users to have Single Sign On (they would be connected to multiple sites automatically) and to support MFA.

**Comment by netscruff** [comment]
There are some extensions and an rpm that will need to be added to the installation:
https://www.mediawiki.org/wiki/Extension:PluggableAuth
https://www.mediawiki.org/wiki/Extension:Shibboleth

Information on basic installation of the rpm package containing the Apache module and shibd daemon are available on our staff wiki:
https://wiki.computecanada.ca/staff/ShibbolethSPInstall

Values for the Shibboleth plugin would be the following:

$wgShibboleth_Username uid or eduPersonPrincipalName (uid@computecanada.ca)
$wgShibboleth_Email = ccPrimaryEmail
$wgShibboleth_DisplayName = displayName
$wgShibboleth_Logout_Base_Url and $wgShibboleth_Logout_Target_Url I think I know what should go here but I can assist at the time of integration to get this working right.

$wgShibboleth_GroupMap = memberOf (posix groups) or ccServiceAccess depending on where the wiki roles are contained so something like this:
array('ccServiceAccess' => 'groups','sysop' => 'wiki_admin','bureaucrat' => 'wiki_editor', '...');

My suggestion would be first integrating the dev docs wiki instance with the dev Shibboleth IdP.

**Comment by sergueev** [comment]
I wanted to provide a bit of update on the progress here. I somewhat successfully installed the Shibboleth service along with Shibboleth and PluggableAuth extensions on docs-dev server with lots of help from Darren. Currently it's associated with the development idp which is https://idp.mit.c3.ca/idp/shibboleth.  The login functionality is perfect: it gets authenticated with the IdP, redirected back to mediawiki with the activated session. However, I am a bit struggling with the logout. The built-in Logout button kills the Mediawiki session but does not deactivate the idp session. The good thing is that one can still manually kill those sessions. Calling /Shibboleth.sso/Logout deactivates the Shibboleth service , while a call to /wiki/Special:UserLogout kills the Mediawiki session. So one of the workarounds would be to create a "Logout" link and insert two urls separated by "?return". I am currently testing this idea.

**Comment by mboisson** [comment]
This is done
