### ISSUE TITLE
Update the Python Avail Wheel page

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/docs#27]
- [x] Missing python 3.9 tab
- [x] Remove older python tabs (3.5)

**Comment by sergueev** [comment]
Added 3.9 to and removed 3.5 from the script generating list of available python modules. Then removed 3.5 tab and added 3.9 tab.

**Comment by ccoulombe** [comment]
Should we remove python 2.7 as well since it died years ago?

**Comment by ccoulombe** [comment]
- [x] Missing 3.10 tab

@sergueev The page is missing Python 3.10 tab, can you please add it?

**Comment by sergueev** [comment]
Python 3.10 tab has been added.
