### ISSUE TITLE
Missing software from Available software page

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/docs#28]
- [x] qcint
- [x] fastp v0.23.1 
- [x] r 4.1.2
- [x] sagemath 9.3, 9.1

**Comment by ccoulombe** [comment]
Having a test suite would help detect those issues.

**Comment by sergueev** [comment]
The issue is in the broken logic in the modules.py script that populates the XML list. I will work on that.

**Comment by stubbsda** [comment]
I think we can also remove the SSE3 (Mammouth) tab from that table as this cluster is no longer a supported Compute Canada system as far as I'm aware.

**Comment by sergueev** [comment]
The problem was that the certain paths for specific architectures were missing in the configuration file. As a result the script didn't see all the architecture specific modules. Now the multiple config files have been generated for each of the avx512, avx2, avx, sse3 architectures and the appropriate changed were also made to the modules.py script. This seems to fix the missing modules issue.

**Comment by stubbsda** [comment]
It does now seem to generate all the versions Nikolai but the ordering of the versions is quite bizarre, e.g. for the R module I see the list
4.1.2, 3.6.0, 3.6.1, 4.1.0, 4.0.5, 3.4.4, 4.0.0, 4.0.2, 3.5.1, 3.5.2
Is there a way to get the list of versions ordered numerically from lowest to highest?

**Comment by ccoulombe** [comment]
The version should be sorted using : https://packaging.pypa.io/en/latest/version.html

```
>>> vstr = list(map(str.strip, '4.1.2, 3.6.0, 3.6.1, 4.1.0, 4.0.5, 3.4.4, 4.0.0, 4.0.2, 3.5.1, 3.5.2'.split(',')))
>>> sorted(map(parse, vstr), reverse=True)
[<Version('4.1.2')>, <Version('4.1.0')>, <Version('4.0.5')>, <Version('4.0.2')>, <Version('4.0.0')>, <Version('3.6.1')>, <Version('3.6.0')>, <Version('3.5.2')>, <Version('3.5.1')>, <Version('3.4.4')>]

```

**Comment by sergueev** [comment]
Ok, I will check that idea with sorting. The reason the versions are all mixed up is because we read them from different Core dirs, and paths. And the versions are stored as strings I believe, so I didn't bother to sort them, but simply joined them everytime the script sees a different version.

**Comment by stubbsda** [comment]
You can use Charles' proposed Python code for that I guess - ordering it from most to least recent is just as good as the other orientation, the main idea is to avoid the current version disorder.

**Comment by ccoulombe** [comment]
@sergueev This issue is only missing the sorting. The missing software seems to be correctly added.

**Comment by sergueev** [comment]
Here is an update. Sorting has been added, so now the version values for each package are all sorted.
