### ISSUE TITLE
Add Python 3.11 tab

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/docs#32]
Add 3.11 tab to the Available Python wheel page.

**Comment by ccoulombe** [comment]
@sergueev can you add the tab please?

**Comment by stubbsda** [comment]
Yes, I think Nikolai is the one who will need to make various modifications to his script for reading the list of Python-3.11 wheels and adding a tab to the _Available Python wheels_ page.

**Comment by sergueev** [comment]
Ok, will add the tab for Python 3.11

**Comment by sergueev** [comment]
Done. Added Python 3.11 tab.
