### ISSUE TITLE
Wiki search varies

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/docs#34]
On the wiki, when using the search box.

### 1) Google Search results
Some pages are searched by Google Search, but others are not, for example : 
- AlphaFold
- Narval

But the Python page is searched.

In your browser, using Google as search engine, if you do `alphafold site:https://docs.alliancecan.ca/wiki/AlphaFold` it returns 
```
Your search - alphafold site:https://docs.alliancecan.ca/wiki/AlphaFold - did not match any documents.
```
It seems that some pages are not indexed.

### 2) Redirection from the search box
Somes pages are redirected no matter the case, for example, if you search for `narval`, you'll get redirected to the `Narval` page.

**Comment by mboisson** [comment]
Seems fixed now ?

**Comment by ccoulombe** [comment]
A very recently added page `nvtop`, is indeed found via Google Search:
```
nvtop site:https://docs.alliancecan.ca/wiki
```
(likewise from the wiki)

**Comment by ccoulombe** [comment]
MPI4py works too :tada:
