### ISSUE TITLE
Available Python Wheels page needs updating

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/docs#4]
Currently, it only list wheels for `generic, avx2`, missing wheels for `avx` (Hélios) or specific `avx512`.

We could join wheels of different archs on the page. Or have tabs for architecture. Downside of tabs is that it would make the page less usable as it would have tabs inside tabs.

With the new structure of the wheelhouse (gentoo and nix), how do we represent that on the page? Or we don't and join wheels.

Note : the script will be backward compatible so one can find wheels independently from Gentoo or Nix or use the pip config file.

**Comment by ccoulombe** [comment]
Or the tabs are for the architecture and the python compatibility is listed as a column, like the script does on CLI

**Comment by stubbsda** [comment]
We can certainly contemplate the exterior product of these two axes (CPU architecture and Python versions), which however would give us 20+ tabs and make the tab header possibly illegible. Tabs within tabs is another idea but I'm not sure if the current tab extension supports this (an experiment for docs-dev, no doubt). The ultimate solution may be a tab for the dominant axis (which is more significant, Python versions or CPU architctures?) with a table inside the tab that lists the module name and the other axis.

**Comment by ccoulombe** [comment]
Actually, no `generic` wheel such as `numpy` is listed on any tabs!!

**Comment by stubbsda** [comment]
Hmm, probably something to bring up in the rsnt-documentation channel to see what light Nikolai can shed on the situation for `generic` Python wheels.

**Comment by ccoulombe** [comment]
The columns should be : `name` and `version` only.

**Comment by sergueev** [comment]
Indeed, it's what I meant too. The other columns just look obsolete. I will fix it.
