### ISSUE TITLE
Simplifying the available software page

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/docs#6]
Collapse the multiples lines into a single line for each app
Drop the prerequisites part, since this is the only thing that varies

**Comment by mboisson** [comment]
@sergueev can you provide an update ?

**Comment by sergueev** [comment]
The python script responsible for generating has been modified to reflect the following changes:
- multiples lines are collapsed into a single line for each app
- new column "Versions" is added to list all possible versions for each app
- the prerequisites part is dropped from the Description 
I think the issue has been resolved and can be closed now.

**Comment by mboisson** [comment]
I don't see those changes on github, i.e. here: 
https://github.com/ComputeCanada/wiki_module_bot

 ? Please push the changes before closing,

**Comment by sergueev** [comment]
All the changes are pushed to git. Closing the issue.
