### ISSUE TITLE
Making modules installed with StdEnv/2020 visible on the Available software page

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/docs#8]
This may require just a change of configuration to the configuration : 
https://github.com/ComputeCanada/wiki_module_bot/blob/master/cvmfs-client-dev.cfg

**Comment by sergueev** [comment]
I have experimented a bit on cvmfs-client-dev and modified the configuration file cvmfs-client-dev.cfg to include the path to the 2020/Core. The modules.py script seems to accept both paths (space separated), and the resulting output seems to contain all the available software from both environments. It looks like no further modifications are needed for the modules.py script.

**Comment by mboisson** [comment]
Is this done ? If so, we can close it.

**Comment by sergueev** [comment]
The software update scripts reads in the path from the configuration file. I have added the path to the StdEnv/2020 env and the script seems have taken that path variable successfully. The appropriate module tabs on docs seem to be populated without any problem. Closing this issue for now.
